.PHONY: help sync up down logs ps reset lint fmt fmt-check type test check ci migrate migrate-new db-shell

help:  ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-18s\033[0m %s\n", $$1, $$2}'

# ---------------------------------------------------------------------------
# Dependency management
# ---------------------------------------------------------------------------
sync:  ## Sync the uv workspace
	uv sync --all-extras

# ---------------------------------------------------------------------------
# Dev infrastructure
# ---------------------------------------------------------------------------
up:  ## Bring up the full dev stack
	docker compose --env-file .env up -d

down:  ## Stop the dev stack (preserve volumes)
	docker compose down

logs:  ## Tail logs from every service
	docker compose logs -f --tail=200

ps:  ## Show dev stack status
	docker compose ps

reset:  ## Stop everything and WIPE all volumes
	docker compose down -v

db-shell:  ## Open a psql shell on the meridian db
	docker compose exec postgres psql -U meridian -d meridian

# ---------------------------------------------------------------------------
# Quality gates
# ---------------------------------------------------------------------------
lint:  ## Ruff lint
	uv run ruff check .

fmt:  ## Ruff format
	uv run ruff format .

fmt-check:  ## Ruff format in check mode
	uv run ruff format --check .

type:  ## Mypy strict typecheck (installed packages + migrations)
	uv run mypy \
	  -p meridian_contracts \
	  -p meridian_telemetry \
	  -p meridian_guardrails \
	  -p meridian_db \
	  -p meridian_output_validator \
	  -p meridian_prompt_assembler \
	  -p meridian_orchestrator \
	  -p meridian_prompt_registry \
	  -p meridian_model_gateway \
	  -p meridian_retrieval_client \
	  -p meridian_tool_executor \
	  -p meridian_evaluator
	uv run --group migrations mypy migrations

test:  ## Pytest
	uv run pytest

check: lint fmt-check type test  ## Run every quality gate (mirrors CI)

ci: check  ## Alias used by .github/workflows/ci.yml

# ---------------------------------------------------------------------------
# Migrations
# ---------------------------------------------------------------------------
migrate:  ## Apply Alembic migrations
	uv run --group migrations alembic upgrade head

migrate-new:  ## Create a new autogenerated migration (requires MSG="message")
	uv run --group migrations alembic revision --autogenerate -m "$(MSG)"

bootstrap-prompts:  ## Load prompts/*.yaml into the registry and activate in dev
	uv run --group bootstrap python scripts/bootstrap_prompts.py --activate --env dev

regression:  ## Run offline regression against all datasets
	uv run python -m meridian_evaluator.cli \
	  --dataset datasets/classifier_v1.yaml --client stub --registry file
	uv run python -m meridian_evaluator.cli \
	  --dataset datasets/grounded_qa_v1.yaml --client stub --registry file
